name: "Pull Request Labeler"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/labeler@v5
      with:
        configuration-path: .github/configs/labeler.yml
        sync-labels: true